version: 1
update_configs:
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "fix"
      include_scope: true
    default_labels:
      - dependencies
  - package_manager: "github_actions"
    directory: "/"
    update_schedule: "daily"
    commit_message:
      prefix: "ci"
      include_scope: true
    default_labels:
      - dependencies